service: validation-service

frameworkVersion: "2"

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-iam-roles-per-function
  - serverless-newrelic-lambda-layers

useDotenv: true

custom:
  newRelic:
    accountId: ${env:NR_ACCOUNT_ID}
    apiKey: ${env:NR_API_KEY}
    enableExtension: true
    enableIntegration: true
    enableDistributedTracing: true
    logEnabled: true
    cloudWatchFilter: "*"
    debug: true

  defaultStage: dev
  defaultRegion: eu-central-1
  environment: ${file(.env):${self:provider.stage}, file(.env):default}

cors:
  origins: 
    - https://*.newrelic.com
    - https://*.newrelic.org
  headers:
   - origin
   
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${env:STAGE, self:custom.defaultStage}
  region: ${env:REGION, self:custom.defaultRegion}
  environment:
    TEST: ${env:TEST, 'default_value'}

functions:
  validate:
    handler: src/functions/validator.validate
    description: Validates organization with Tech Soup API
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - rds-data:*
        Resource: "arn:aws:rds:*:*:cluster:${env:DATABASE_CLUSTER_NAME}"
      - Effect: "Allow"
        Action:
          - secretsmanager:*
        Resource: "arn:aws:secretsmanager:*:*:*"
    events:
      - http:
          path: /validate
          method: get
          cors: true
    memorySize: 512
  validate-token:
    handler: src/functions/validate-token.validateToken
    description: Validates token - checks if token was already used (checks the database)
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - rds-data:*
        Resource: "arn:aws:rds:*:*:cluster:${env:DATABASE_CLUSTER_NAME}"
      - Effect: "Allow"
        Action:
          - secretsmanager:*
        Resource: "arn:aws:secretsmanager:*:*:*"
    events:
      - http:
          path: /validate-token
          method: get
          cors: true
    memorySize: 512
  validate-account:
    handler: src/functions/validate-account.validateAccount
    description: Validates account - checks what is the status of provided account (checks the database)
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - rds-data:*
        Resource: "arn:aws:rds:*:*:cluster:${env:DATABASE_CLUSTER_NAME}"
      - Effect: "Allow"
        Action:
          - secretsmanager:*
        Resource: "arn:aws:secretsmanager:*:*:*"
    events:
      - http:
          path: /validate-account
          method: get
          cors: true
    memorySize: 512
  save-attempt:
    handler: src/functions/save-attempt.saveAttempt
    description: Saves validation attempt to database
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - rds-data:*
        Resource: "arn:aws:rds:*:*:cluster:${env:DATABASE_CLUSTER_NAME}"
      - Effect: "Allow"
        Action:
          - secretsmanager:*
        Resource: "arn:aws:secretsmanager:*:*:*"
    events:
      - http:
          path: /attempts
          method: post
          cors: true
    memorySize: 512
  get-validation-history:
    handler: src/functions/get-validation-history.getValidationHistory
    description: Returns the validation history from the database for selected account
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - rds-data:*
        Resource: "arn:aws:rds:*:*:cluster:${env:DATABASE_CLUSTER_NAME}"
      - Effect: "Allow"
        Action:
          - secretsmanager:*
        Resource: "arn:aws:secretsmanager:*:*:*"
    events:
      - http:
          path: /attempts
          method: get
          cors: true
    memorySize: 512
  manual-approval:
    handler: src/functions/manual-approval.manualApprove
    description: Saves information about account which should be validate mannually
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - rds-data:*
        Resource: "arn:aws:rds:*:*:cluster:${env:DATABASE_CLUSTER_NAME}"
      - Effect: "Allow"
        Action:
          - secretsmanager:*
        Resource: "arn:aws:secretsmanager:*:*:*"
    events:
      - http:
          path: /manual-approve
          method: post
          cors: true
    memorySize: 512
  get-llr:
    handler: src/functions/get-lookup-response.getLookupResponse
    description: Returns the lookup large response data for given org id
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - rds-data:*
        Resource: "arn:aws:rds:*:*:cluster:${env:DATABASE_CLUSTER_NAME}"
      - Effect: "Allow"
        Action:
          - secretsmanager:*
        Resource: "arn:aws:secretsmanager:*:*:*"
    events:
      - http:
          path: /large-response
          method: get
          cors: true
    memorySize: 512
  update-llr:
    handler: src/functions/update-llr.updateLookupLargeResponse
    description: Updates client data with LLR of existing clients
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - rds-data:*
        Resource: "arn:aws:rds:*:*:cluster:${env:DATABASE_CLUSTER_NAME}"
      - Effect: "Allow"
        Action:
          - secretsmanager:*
        Resource: "arn:aws:secretsmanager:*:*:*"
    events:
      - http:
          path: /update
          method: get
          cors: true
    memorySize: 512
