service: validation-service

frameworkVersion: '2'

plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-iam-roles-per-function
  - serverless-newrelic-lambda-layers

useDotenv: true

custom:
  newRelic:
    accountId: ${env:NR_ACCOUNT_ID}
    apiKey: ${env:NR_API_KEY}
    enableExtension: false
    enableIntegration: true
    logEnabled: true
    cloudWatchFilter: "*"

  defaultStage: dev
  defaultRegion: eu-central-1
  environment: ${file(.env):${self:provider.stage}, file(.env):default}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${env:STAGE, self:custom.defaultStage}
  region: ${env:REGION, self:custom.defaultRegion}
  environment:
    TEST: ${env:TEST, 'default_value'}

functions:
  validate:
    handler: src/functions/validator.validate
    description: Validates organization with Tech Soup API
    events:
      - http:
          path: /validate
          method: get
          cors: true
    memorySize: 512
  validate-token:
    handler: src/functions/validate-token.validateToken
    description: Validates token - checks if token was already used (checks the database)
    timeout: 12
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - rds-data:*
        Resource: "arn:aws:rds:*:*:cluster:${env:DATABASE_CLUSTER_NAME}"
      - Effect: "Allow"
        Action:
          - secretsmanager:*
        Resource: "arn:aws:secretsmanager:*:*:*"
    events:
      - http:
          path: /validate-token
          method: get
          cors: true
    memorySize: 512
  validate-account:
    handler: src/functions/validate-account.validateAccount
    description: Validates account - checks what is the status of provided account (checks the database)
    timeout: 12
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - rds-data:*
        Resource: "arn:aws:rds:*:*:cluster:${env:DATABASE_CLUSTER_NAME}"
      - Effect: "Allow"
        Action:
          - secretsmanager:*
        Resource: "arn:aws:secretsmanager:*:*:*"
    events:
      - http:
          path: /validate-account
          method: get
          cors: true
    memorySize: 512
  save-attempt:
    handler: src/functions/save-attempt.saveAttempt
    description: Saves validation attempt to database
    timeout: 12
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - rds-data:*
        Resource: "arn:aws:rds:*:*:cluster:${env:DATABASE_CLUSTER_NAME}"
      - Effect: "Allow"
        Action:
          - secretsmanager:*
        Resource: "arn:aws:secretsmanager:*:*:*"
    events:
      - http:
          path: /attempts
          method: post
          cors: true
    memorySize: 512
  get-validation-history:
    handler: src/functions/get-validation-history.getValidationHistory
    description: Returns the validation history from the database for selected account
    timeout: 12
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - rds-data:*
        Resource: "arn:aws:rds:*:*:cluster:${env:DATABASE_CLUSTER_NAME}"
      - Effect: "Allow"
        Action:
          - secretsmanager:*
        Resource: "arn:aws:secretsmanager:*:*:*"
    events:
      - http:
          path: /attempts
          method: get
          cors: true
    memorySize: 512
